theme:
  name: material
  features:
  - content.code.copy
site_name: e-footprint documentation

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences

docs_dir: docs_sources/generated_mkdocs_sourcefiles

site_dir: docs

nav:
- Introduction: index.md
- Tutorial: tutorial.md
- Explanation:
  - Explanation overview: explanation_overview.md
  - e-footprint scope: efootprint_scope.md
  - Why e-footprint ?: why_efootprint.md
  - How to get started: get_started.md
  - The e-footprint methodology: methodology.md
  - e-footprint design choices deep dive: design_deep_dive.md
- How-to guides:
    - How to model a machine learning workflow: machine_learning_workflow.md
    - How to model a database: database_modeling.md
    - How to model the evolution of a system across time: evolution_across_time.md
    - How to model server to server interaction: server_to_server_interaction.md
- e-footprint objects reference:
  - How to read the object reference: object_reference.md
  - Hardware:
      - Servers:
          - Server: Server.md
          - GPU Server: GPUServer.md
          - Boavizta cloud server: BoaviztaCloudServer.md
      - Devices: Device.md
      - Network: Network.md
      - Storage: Storage.md
      - Edge:
          - Edge device:
              - Edge device (base object): EdgeDevice.md
              - Edge computer:
                - Edge computer: EdgeComputer.md
                - Edge computer RAM: EdgeComputerRAMComponent.md
                - Edge computer CPU: EdgeComputerCPUComponent.md
              - Edge appliance:
                - Edge appliance: EdgeAppliance.md
                - Edge appliance component: EdgeApplianceComponent.md
          - Edge components:
              - RAM component: EdgeRAMComponent.md
              - CPU component: EdgeCPUComponent.md
              - Storage component: EdgeStorage.md

  - Services:
      - Web application:
          - Web application service: WebApplication.md
          - Web application job: WebApplicationJob.md
      - Video streaming:
          - Video streaming service: VideoStreaming.md
          - Video streaming job: VideoStreamingJob.md
      - Gen AI:
          - Gen AI service: GenAIModel.md
          - Gen AI job: GenAIJob.md
  - Usage:
      - Usage pattern: UsagePattern.md
      - Usage journey: UsageJourney.md
      - Usage journey step: UsageJourneyStep.md
      - Job: Job.md
      - GPU job: GPUJob.md
      - Edge:
        - Edge usage pattern: EdgeUsagePattern.md
        - Edge usage journey: EdgeUsageJourney.md
        - Edge function: EdgeFunction.md
        - Edge device need:
          - Edge device need: RecurrentEdgeDeviceNeed.md
          - Recurrent edge workload:
            - Recurrent edge workload: RecurrentEdgeWorkload.md
            - Recurrent edge workload need: RecurrentEdgeWorkloadNeed.md
          - Recurrent edge process:
            - Recurrent edge process: RecurrentEdgeProcess.md
            - Recurrent edge process ram need: RecurrentEdgeProcessRAMNeed.md
            - Recurrent edge process cpu need: RecurrentEdgeProcessCPUNeed.md
            - Recurrent edge process storage need: RecurrentEdgeProcessStorageNeed.md
        - Edge server need: RecurrentServerNeed.md
        - Edge component need:
          - Edge component need: RecurrentEdgeComponentNeed.md
          - Edge storage need: RecurrentEdgeStorageNeed.md
  - System: System.md
  - Country: Country.md
- FAQ:
    - What about best practices ?: best_practices.md
    - What about measurement tools ?: measurement_tools.md
    - What about the build process of the service ?: build_process.md
    - Why only CO2 ?: only_CO2.md
- External links: links.md
- Changelog: Changelog.md